---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

<style>
body {text-align: justify}
</style>

### Entangled Footprints: Understanding Urban Neighbourhoods by Measuring Variability of Distance, Diversity, and Direction of Flows in Singapore

**Abstract**

Human mobility has been a long-standing interest in Geography and has been approached from both spatial and relational perspectives. Traditionally many such approaches use census or survey data that is resource-intensive to collect and often has a limited spatio-temporal scope. The advent of new technologies (e.g. geosocial media platforms) provides opportunities to overcome these limitations and, if properly treated, can yield more granular insights about human mobility. In this paper, we use a de-identified Location-Based Service (LBS) dataset sent in Singapore from 2012 to 2016 to investigate this potential regarding understanding the spatial footprints of urban neighbourhoods.

We construct home-to-destination networks of each user based on the inferred home locations. In aggregated form, the networks allows us to analyze three specific mobility indicators, namely the distance, diversity,  and direction of urban interactions, at the neighborhood level . By mapping these three characteristics of a spatial footprint of each neighbourhood, we can capture the nuances in the position of individual neighbourhoods within the larger urban system. Besides, we further conduct a spatial regression analysis to help illustrate the variation in distance and diversity of flows. The result reveals both socio-economic characteristics and built environment structure impact the mobility footprints, shaping different movement patterns within and across neighbourhoods.

Keywords: Human Mobility · Location-Based-Services · Activity Space · Twitter · Spatial Networks · Urban Neighbourhoods  · Singapore
